In [1]:
import pandas as pd

In [2]:
path_to_measurements = 'data'

In [3]:
from raptor_functions.supervised.preprocess import preprocess_all_files
df = preprocess_all_files(path_to_measurements, has_label= False)

In [4]:
df.to_csv('data/data.csv')

In [5]:
df.columns

Index(['timesteps', 'sensor_1', 'sensor_2', 'sensor_3', 'sensor_4', 'sensor_5',
       'sensor_6', 'sensor_7', 'sensor_8', 'sensor_9', 'sensor_10',
       'sensor_11', 'sensor_12', 'sensor_13', 'sensor_14', 'sensor_15',
       'sensor_16', 'sensor_17', 'sensor_18', 'sensor_19', 'sensor_20',
       'sensor_21', 'sensor_22', 'sensor_23', 'sensor_24', ' Humidity (r.h.)',
       'exp_unique_id', 'measurement_stage', 'date_exp', 'time_elapsed',
       'datetime_exp_start', 'filename', 'exp_name', 'repeat_no'],
      dtype='object')

In [6]:
FEATURES = ['sensor_1', 'sensor_2', 'sensor_3', 'sensor_4', 'sensor_5',
       'sensor_6', 'sensor_7', 'sensor_8', 'sensor_9', 'sensor_10',
       'sensor_11', 'sensor_12', 'sensor_13', 'sensor_14', 'sensor_15',
       'sensor_16', 'sensor_17', 'sensor_18', 'sensor_19', 'sensor_20',
       'sensor_21', 'sensor_22', 'sensor_23', 'sensor_24']

In [7]:
results = ['pig','pig',
'non-pig', 'non-pig',
'pig','pig',
'pig','pig',
'pig','pig',
'pig','pig',
'non-pig','non-pig',
'non-pig','non-pig']

In [8]:
lst = []
for i, group in enumerate(df.groupby('exp_unique_id')):
    group[1]['result'] = results[i]
    lst.append(group[1])
df = pd.concat(lst)

In [9]:
df

,timesteps,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,sensor_6,sensor_7,sensor_8,sensor_9,...,Humidity (r.h.),exp_unique_id,measurement_stage,date_exp,time_elapsed,datetime_exp_start,filename,exp_name,repeat_no,result
0,1,476.250,397.227,492.131,479.955,497.618,195.377,340.400,396.126,110.550,...,47.24,0,baseline,1/8/2022,0.00,13:50:25,Test_1_20220801_13_50.txt,Test 24,1,pig
1,2,474.049,395.030,491.355,477.726,496.040,194.976,339.531,395.030,110.340,...,47.18,0,baseline,1/8/2022,0.25,13:50:25,Test_1_20220801_13_50.txt,Test 24,1,pig
2,3,474.781,395.030,491.355,476.987,496.040,194.976,339.531,394.484,110.340,...,47.18,0,baseline,1/8/2022,0.50,13:50:25,Test_1_20220801_13_50.txt,Test 24,1,pig
3,4,474.781,395.030,492.131,477.726,496.828,194.776,339.531,394.484,110.131,...,47.18,0,baseline,1/8/2022,0.75,13:50:25,Test_1_20220801_13_50.txt,Test 24,1,pig
4,5,475.514,393.939,492.909,476.250,496.828,194.776,339.531,393.939,110.131,...,47.11,0,baseline,1/8/2022,1.00,13:50:25,Test_1_20220801_13_50.txt,Test 24,1,pig
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,180,473.319,401.678,492.131,473.319,496.040,198.824,341.709,399.442,111.498,...,50.27,14,wait,1/8/2022,44.75,13:38:39,Test_1_20220801_13_38.txt,Test 24,1,non-pig
180,181,471.864,400.558,491.355,474.049,496.828,198.414,341.272,399.442,111.498,...,50.27,14,wait,1/8/2022,45.00,13:38:39,Test_1_20220801_13_38.txt,Test 24,1,non-pig
181,182,472.591,400.558,492.131,474.781,497.618,198.414,341.272,400.000,111.604,...,50.27,14,wait,1/8/2022,45.25,13:38:39,Test_1_20220801_13_38.txt,Test 24,1,non-pig
182,183,473.319,401.678,492.131,473.319,496.040,198.414,340.400,400.000,111.604,...,50.27,14,wait,1/8/2022,45.50,13:38:39,Test_1_20220801_13_38.txt,Test 24,1,non-pig
183,184,473.319,401.117,491.355,474.781,496.040,198.414,340.836,400.000,111.392,...,50.27,14,wait,1/8/2022,45.75,13:38:39,Test_1_20220801_13_38.txt,Test 24,1,non-pig

In [10]:
from raptor_functions.supervised.feature_extraction import get_training_features
df_f = get_training_features(df,features=FEATURES)

Extracting all features

Feature Extraction: 100%|██████████| 20/20 [00:14<00:00,  1.43it/s]

:

:

In [ ]:
import mlflow
from raptor_functions.supervised.train import train_experiments
mlflow.end_run()
train_experiments(df_f, n_trials=5, study_name='demo-exp')