In [1]:
import sys
PACKAGE_FOLDER = "/Users/danielfiuzadosil/Documents/GitHub/raptor_functions/raptor_functions"
PACKAGE_FOLDER = "/Users/amash/Insync/GDrive/Projects/Raptor/raptor_functions"
sys.path.insert(0, PACKAGE_FOLDER)

In [2]:
from raptor_functions.supervised.datasets import get_data
df = get_data('validated_breath_data')

In [3]:
df.head()

,exp_unique_id,exp_name,timesteps,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,sensor_6,sensor_7,...,sensor_22,sensor_23,sensor_24,humidity,measurement_stage,date_exp,time_elapsed,datetime_exp,filename,result
0,0,39A,0.0,316.594,315.854,315.735,313.180,307.498,315.926,316.188,...,103.786,103.404,103.691,52.467,baseline,20/01/2022,0.00,2022-01-20 13:31:47.000,39A_13_31_00.03.txt,Covid
1,0,39A,1.0,316.928,315.854,316.188,313.324,307.331,315.997,316.499,...,103.882,103.357,103.595,45.112,baseline,20/01/2022,0.25,2022-01-20 13:31:47.250,39A_13_31_00.03.txt,Covid
2,0,39A,2.0,315.711,316.045,315.759,313.514,307.403,315.950,315.926,...,104.001,103.452,103.643,35.637,baseline,20/01/2022,0.50,2022-01-20 13:31:47.500,39A_13_31_00.03.txt,Covid
3,0,39A,3.0,316.499,315.854,315.329,312.536,308.095,315.854,316.403,...,104.073,103.380,103.619,28.102,baseline,20/01/2022,0.75,2022-01-20 13:31:47.750,39A_13_31_00.03.txt,Covid
4,0,39A,4.0,317.048,315.568,315.520,312.679,307.188,315.926,316.451,...,103.929,103.357,103.428,26.794,baseline,20/01/2022,1.00,2022-01-20 13:31:48.000,39A_13_31_00.03.txt,Covid

In [4]:
FEATURES = ['sensor_1', 'sensor_2',
       'sensor_3', 'sensor_4', 'sensor_5', 'sensor_6', 'sensor_7', 'sensor_8',
       'sensor_9', 'sensor_10', 'sensor_11', 'sensor_12', 'sensor_13',
       'sensor_14', 'sensor_15', 'sensor_16', 'sensor_17', 'sensor_18',
       'sensor_19', 'sensor_20', 'sensor_21', 'sensor_22', 'sensor_23',
       'sensor_24']

In [5]:
FEATURES = [
    "sensor_1",
    "sensor_2",
    "sensor_3",
    "sensor_4",
    "sensor_5",
    "sensor_6",
    "sensor_7",
    "sensor_8",
    "sensor_9",
    "sensor_10",
    "sensor_11",
    "sensor_12",
    "sensor_13",
    "sensor_14",
    "sensor_15",
    "sensor_16",
    "sensor_17",
    "sensor_18",
    "sensor_19",
    "sensor_20",
    "sensor_21",
    "sensor_22",
    "sensor_23",
    "sensor_24"
]

In [6]:
df.head()

,exp_unique_id,exp_name,timesteps,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,sensor_6,sensor_7,...,sensor_22,sensor_23,sensor_24,humidity,measurement_stage,date_exp,time_elapsed,datetime_exp,filename,result
0,0,39A,0.0,316.594,315.854,315.735,313.180,307.498,315.926,316.188,...,103.786,103.404,103.691,52.467,baseline,20/01/2022,0.00,2022-01-20 13:31:47.000,39A_13_31_00.03.txt,Covid
1,0,39A,1.0,316.928,315.854,316.188,313.324,307.331,315.997,316.499,...,103.882,103.357,103.595,45.112,baseline,20/01/2022,0.25,2022-01-20 13:31:47.250,39A_13_31_00.03.txt,Covid
2,0,39A,2.0,315.711,316.045,315.759,313.514,307.403,315.950,315.926,...,104.001,103.452,103.643,35.637,baseline,20/01/2022,0.50,2022-01-20 13:31:47.500,39A_13_31_00.03.txt,Covid
3,0,39A,3.0,316.499,315.854,315.329,312.536,308.095,315.854,316.403,...,104.073,103.380,103.619,28.102,baseline,20/01/2022,0.75,2022-01-20 13:31:47.750,39A_13_31_00.03.txt,Covid
4,0,39A,4.0,317.048,315.568,315.520,312.679,307.188,315.926,316.451,...,103.929,103.357,103.428,26.794,baseline,20/01/2022,1.00,2022-01-20 13:31:48.000,39A_13_31_00.03.txt,Covid

In [7]:
from raptor_functions.supervised.feature_extraction import get_training_features, get_all_features

In [8]:
df_f = get_training_features(df,features=FEATURES)

Extracting all features

Feature Extraction: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 20/20 [01:02<00:00,  3.14s/it]

Selecting relevant features

/Users/amash/anaconda3/envs/ra37/lib/python3.7/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

[17:26:13] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[17:26:50] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[17:27:58] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[17:28:56] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

In [ ]:
import mlflow
from raptor_functions.supervised.train import train_experiments

mlflow.end_run()

train_experiments(df_f, n_trials=5, study_name='demo-exp')